# Schemes
 scheme: Muse
#scheme: Mist
# scheme: Pisces
#scheme: Gemini

 social:
  GitHub: https://github.com/ChessMax || fab fa-github
  E-Mail: mailto:chessmax@yandex.ru || fa fa-envelope
  Twitter: https://twitter.com/MaxStranger7 || fab fa-twitter
  FB Page: https://www.facebook.com/ChessMax || fab fa-facebook
  StackOverflow: https://stackoverflow.com/users/423703/chessmax || fab fa-stack-overflow
  YouTube: https://www.youtube.com/user/InetPC7 || fab fa-youtube
#  Instagram: https://instagram.com/yourname || fab fa-instagram
#  Skype: skype:yourname?call|chat || fab fa-skype

 footer:
  since: 2011
  powered: false
  
 follow_me:
  Twitter: https://twitter.com/MaxStranger7 || fab fa-twitter
#Telegram: https://t.me/channel_name || fab fa-telegram
#WeChat: /images/wechat_channel.jpg || fab fa-weixin
  RSS: /atom.xml || fa fa-rss
  
 menu:
   home: / || fa fa-home
   archives: /archives/ || fa fa-archive
   categories: /categories/ || fa fa-list-alt
   tags: /tags/ || fa fa-tags
   about: /about/ || fa fa-user 
   
 github_banner:
   enable: true
   permalink: https://github.com/ChessMax
   title: Follow me on GitHub  
   
 avatar:
   url: /uploads/avatar.jpg
   
 site_state: false
 tag_icon: true

 reading_progress:
   enable: true
   # Available values: left | right
   start_at: left
   # Available values: top | bottom
   position: top
   reversed: false
   color: "#37c6c0"
   height: 2px  
   
# Utterances
# For more information: https://utteranc.es
 utterances:
   enable: true
   repo: "ChessMax/chessmax.ru" # Github repository name
   # Available values: pathname | url | title | og:title
   issue_term: pathname
   # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
   theme: github-light  
  
# Demo: https://utteranc.es/  http://trumandu.github.io/about/
 utteranc:
   enable: true
   repo: "ChessMax/chessmax.ru" #Github repo such as :TrumanDu/comments
   pathname: pathname
   # theme: github-light,github-dark,github-dark-orange
   theme: github-light
   cdn: https://utteranc.es/client.js
   # If you want to modify priority, please config in **hexo**
   #priority:
     
# Local search
# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
 local_search:
   enable: true
   # If auto, trigger search by changing input.
   # If manual, trigger search by pressing enter key or search button.
   trigger: auto
   # Show top n results per article, show all results by setting to -1
   top_n_per_article: 1
   # Unescape html strings to the readable one.
   unescape: false
   # Preload the search data when the page loads.
   preload: false
   
 sidebar:
   display: hide